### ISSUE TITLE
Entries index gets corrupted (flat files db)

### ISSUE THREAD

**Issue by brainexcerpts** [pivotx/PivotX#1] opened 2021-12-20 05:02 UTC
Sometimes inside my weblog section 80% of my entries suddenly stop showing off. I regularly have to do a "rebuild index" in order for them to display again. Do you have any pointers as to where I should look for bugs in the php code? Alternatively do you think switching the db from flat files to mysql could potentially fix that bug and is it straightforward to do. (I love flat files for their simplicity but maybe with 2000 visits a month I already reached the limit of what they can handle?). It's really puzzling because I thought only read operations would occur on visits, but still, the index seems to get corrupted while I'm not even editing anything on the administration side.

Disclaimer: I know development and support was discontinued a long time ago but the cost of switching to another CMS is for now too heavy for me. Hopefully you can give me a few hints and can fix that recurrent issue. thanks a lot.

**Comment by hansfn** [comment] 2021-12-20 08:43
Hans from the former dev team here. I also loved the flat file database, but unfortunately I have no hints about how to resolve the corruption issue. It seems to be connected to comments (which indeed alter the database). If disabling comments (for all existing entries - not just changing the global setting) isn't an option, I recommend switching to a MySQL database - no corruption then.

1. I don't remember if we have support for converting from flat file to MySQL. It's so long time ago ...
2. If you are able to make a reproducible situation that causes corruption, I'm probably able to fix it. (You can test with a copy of your installation and so on.)

**Comment by brainexcerpts** [comment] 2021-12-21 03:50
Thank you for the swift answer, this is really helpful :) At least I know where to start, I'll try to see if I can reproduce the issue with comments. I'll get back to you but It'll take me quite some time before I can work on this tough.

I found a script to [export entries from flat files to mysql](http://forum.pivotx.net/viewtopic.php?f=2&t=3375) as a last resort.

**Comment by philippschmidtbauer** [comment] 2022-04-06 14:24
Hi - also having the described issue ––> the majority of my entries is gone, users cannot browse them :(

**And** in addition to that I am not able to rebuild the index - this is really strange. Rebuilding search index works fine for me. But rebuilding the "main" index is not working, clicking the button just opens an empty white page at http://www.mypage.de/weblog/pivotx/index.php?page=buildindex

I've invested some hours already in trying to find out, how to get my entries back.

Wondering if you have some ideas - I'd really appreciate it!

- PHP version: 7.4.28-he.0
- PivotX 3.0.0 Release Candidate 2

**Comment by hansfn** [comment] 2022-04-06 14:31
These are different issues. brainexcerpts can rebuild the index and the entries reappear. In your case 

> rebuilding the "main" index is not working, clicking the button just opens an empty white page

A white page (of death) means there is some internal error that you can find in the webserver error log. If you are lucky, you can get the errors to appear in the browser by enabling debugging in the PivotX configuration.

**Comment by philippschmidtbauer** [comment] 2022-04-06 14:47
This is what I get when trying to rebuild the flat entries index:

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function makeArchiveArray(), 0 passed in /www.mypage.de/weblog/pivotx/pages.php on line 2183 and exactly 2 expected in /www.mypage.de/weblog/pivotx/lib.php:2462 

Stack trace: 
#0 /www.mypage.de/weblog/pivotx/pages.php(2183): makeArchiveArray() 
#1 /www.mypage.de/weblog/pivotx/lib.php(272): pageBuildindex() 
#2 /www.mypage.de/weblog/pivotx/index.php(21): displayPage() 
#3 {main} thrown in /www.mypage.de/weblog/pivotx/lib.php on line 2462
```

**Comment by hansfn** [comment] 2022-04-06 14:56
OK, that is something I can work with. If you don't get any feedback by Monday, leave a ping here.

**Comment by philippschmidtbauer** [comment] 2022-04-06 15:19
Also I've managed to get capture this debug output, when trying to open a list of entries where entries are missing:

```
2022-04-06 17:15:23 - 0.019 -- modules/module_debug.php:415 / userErrorHandler() --  ( 6843288 ) 
Warning: Invalid argument supplied for foreach(). (in 'modules/entries_flat.php' on line 506)
Warning: count(): Parameter must be an array or an object that implements Countable. (in 'modules/module_smarty.php' on line 3467)


2022-04-06 17:15:23 - 0.126 -- modules/entries_flat.php:1452 / write_entry_index() --  ( 6997920 ) 
Save entry index (1,index-standard-00000.php)


2022-04-06 17:15:23 - 0.127 -- modules/module_debug.php:415 / userErrorHandler() --  ( 7142032 ) 
Warning: Invalid argument supplied for foreach(). (in 'modules/entries_flat.php' on line 506)
Warning: count(): Parameter must be an array or an object that implements Countable. (in 'modules/module_parser.php' on line 1565)
```

**Comment by hansfn** [comment] 2022-04-09 14:18
@philippschmidtbauer, your fatal error has been fixed in [commit 125fe8aa697e984a49340315b680c43365dcd416](https://github.com/pivotx/PivotX/commit/125fe8aa697e984a49340315b680c43365dcd416). Unless you can report actual problems related to the warnings, I will not spend time on it. 

PS! Further problems not related to index corruption, should be filed as new issues.

**Comment by philippschmidtbauer** [comment] 2022-04-10 15:18
Thank you so much hansfn - the fix helped me to rebuild my flat entries index and now visitors of my page can see all entries again - I am more than happy! Thank you so much!

**Comment by brainexcerpts** [comment] 2022-04-28 09:15
Hello, so I finally had a bit of time to investigate the issue.

Reminder: I'm in flat file mode and some of my blog entry would randmoly dissappear. Maintance -> Rebuild would fix that.

More precisely I now know that:

- `\www\pivotx\db\standard-00000\index-standard-00000.php` 
  gets corrupted with its content suddenly becoming `<?php /* pivot */ die(); ?>b:0;`
- `\www\pivotx\db\standard-00100\index-standard-00100.php`
  stays the same (I have 138 entries in total)
  
Every time it occurs no new comments are written, however, `spamkiller.2022-04.log` shows me that spam comments where 
blocked around the same time the issue appears.

I was able to setup a local environment with XAMPP and I wrote the following python scripts 
to simulate hundreds of comment submission in parallel:

    import requests
    from concurrent.futures import ThreadPoolExecutor

    def post_url(args):
        return requests.post(args[0], data=args[1])
        
    form_data = {
        "piv_name" : "qsdf",
        "piv_comment" : "qsdf",
        "spamquiz_answer" : "42",
        "piv_code" : "134", 
        "piv_discreet" : "1",
        "piv_weblog":"weblog",
        "post":"Post Comment",
        "hc4836" : "817460843"    
    }


    nb_requests = 1000
    list_of_urls = [("http://127.0.0.1/entry/134/title-of-my-entry#message", form_data)]*nb_requests


    with ThreadPoolExecutor(max_workers=nb_requests) as pool:
        response_list = list(pool.map(post_url,list_of_urls))

    for response in response_list:
        print(response)
        
I ran the script in several separate command lines,        
unfortunatly I was not able to reproduce the issue. 


I'll be needed a bit of advice to guide me through this debuging if you don't mind.
Do you have suggestions to reproduce this bug, other than the python approach?

Since locally reproducing the bug seems difficult, I was thinking about logging every time the index gets modified and wait until the problem appears again on the actual server. (not ideal since it usually occurs every other days or week)
 - if I insert some logging procedure in `module_db.php/generate_index()` I think I'll be able to capture any activity on the db index right?
 - Do you recommend any built in utility function to easily dump as much as possible info?
 
Finally I have a question around `flock()` and `fwrite()`.
Db write operation seemed to be protected with `flock()` but I saw that it wasn't always the case that a `fwrite` 
was protected with a `flock()` in Pivotx, for instance when writing out spam logs.
Is this normal? Shouldn't we make sure any access to files are protected with a mutex?

Thanks for your help.

**Comment by brainexcerpts** [comment] 2022-05-03 05:00
Ok so I investigated more and here is a report.

I discovered that when using the template:
[[ paging action="digg" showalways=1 ]] in front.tpl 
(In charge of displaying the "previous" and "next" buttons in your weblog page, i.e. the page that list all your blog entries.)

The index gets written. Which means only loading your weblog page writes in the index.

Which lead me to test my bug with the following python script:

```
import requests
from concurrent.futures import ThreadPoolExecutor

def post_url(args):

    response = "ERROR"
    try:
        response = requests.post(args[0], data=args[1])
    except Exception as err:
        print("Exception raised")
        print(err)
    return response
    
    
form_data = {
    "piv_name" : "qsdf",
    "piv_comment" : "qsdf",
    "spamquiz_answer" : "42",
    "piv_code" : "134", 
    "piv_discreet" : "1",
    "piv_weblog":"weblog",
    "post":"Post Comment",
    "hc4836" : "817460843"    
}


nb_requests = 500
list_of_urls = []

for i in range(nb_requests):
    list_of_urls += [("http://127.0.0.1/weblog/weblog", {})]    
    list_of_urls += [("http://127.0.0.1/weblog/weblog", {})]  
    list_of_urls += [("http://192.168.2.100/weblog/weblog", {})]

with ThreadPoolExecutor(max_workers=128) as pool:
    response_list = list(pool.map(post_url,list_of_urls))

for response in response_list:
    print(response)
```

I could not reproduce the bug where the index gets indefinitely corrupted, however, 
running this script and loading the weblog page from another computer's browser on my local network I could display the page with missing entries.

Further investigation showed that: 
reading with loadSerialize() is not protected with any flock(). 
But saveSerialize() temporarily empty out files when writing to them which means sometimes when reading the index the content gets temporarily empty.

Adding flock() in loadSerialize() fixed the above bug although it's not exactly 100% the bug I have on my server it's surely related.

I will work a bit more on it and probably submit a merge request after a more thorough check and clean up of all the flock issues. 


(At this point I think the problem is not specifically related to comments but lack of use of mutex especially when file get reads so I'm tempted to add flocks anywhere a fopen opens occurs whether it's read or write. Also I'm not sure we should use LOCK_NB  which could fail quite often on buzy days I would prefer use flock( ) without it to make the user wait until the lock gets acquired)

**Comment by hansfn** [comment] 2022-05-12 19:26
Thank you for investigating further. 

I'm looking forward to the patch as I most definitely won't have time to fix this myself.

**Comment by brainexcerpts** [comment] 2022-09-18 09:59
I opened a pull request with fix @hansfn

**Comment by hansfn** [comment] 2022-09-18 20:41
Thank you! I'll review the PR. If it looks good, as I expect, I'll merge it quickly for the benefit of other users.

**Closed** 2024-02-21 00:30 UTC
Labels: bug
