### ISSUE TITLE
mysql error (it seems)

### ISSUE THREAD

**Issue by bcmans** [pivotx/PivotX#22] opened 2023-12-11 16:16 UTC
**Describe the bug**

There was a problem with the Database:

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DESC, e.uid DESC ORDER BY e.date DESC LIMIT 8' at line 3

error code 1064

    If you're in the process of setting up PivotX, you should review your [Database connection settings](https://kootenaychristianfellowship.com/dat/pivotx/index.php?page=configuration#section-2).
    If it worked before, you should check if the Mysql database engine is still running on the server (or ask your systems administrator to check for you).

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information:**
 - PivotX version 3.0 rc3
 - PHP version 7.4
 - Web server or browser if relevant

**Additional context**
Website was running fine for several months.
https://kootenaychristianfellowship.com/dat/

**Comment by hansfn** [comment] 2023-12-11 18:09
It seems your site works again. For the benefit of other readers: What did you do - clear cache? If the problem is indeed fixed, just close the issue.

**Comment by brainexcerpts** [comment] 2023-12-12 00:59
![image](https://github.com/pivotx/PivotX/assets/8319592/3aab88dd-25c6-44a1-9d6a-14ec6a209de0)
![image](https://github.com/pivotx/PivotX/assets/8319592/8771b078-7564-40ef-b658-3c9c6d6f918e)

I clicked your link and a few others and it seems to work on my side.

Now maybe it's a bug similar to the flat file db bug in which case it would be triggered quite randomly, you would still have to fix it each time by "re-building the index" in the "maintenance tab", so did you do anything of that sort?

**Comment by bcmans** [comment] 2023-12-13 18:10
yes i did and in the mean time i moved it to a different server (without any problems) will test more on the old server with the hostpapa to see what the problem is. Will keep you informed

**Comment by hansfn** [comment] 2023-12-13 18:13
Try to enable DB query logging on the old server so we get the complete query that fails.

**Comment by hansfn** [comment] 2024-02-21 00:32
Closing until new information is provided.

**Closed by hansfn** 2024-02-21 00:32 UTC
